name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Release (semantic-release root polyrepo)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release || echo "Semantic release finished (or skipped)"

      - name: Publish workspaces via Changesets (if pending changesets)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if pnpm changeset status >/dev/null 2>&1; then
            echo "Applying changesets and publishing...";
            pnpm changeset version;
            pnpm install --lockfile-only;
            pnpm build;
            pnpm changeset publish;
          else
            echo "No changesets to publish";
          fi

      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: sdks/typescript/*/dist
          if-no-files-found: warn
